"""
Markdown audit report generator.

Takes structured analysis findings and produces a clean, readable
markdown report that can be read by humans or handed to a coding agent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Finding:
    """A single finding from an analysis perspective."""

    title: str
    description: str
    file_path: str
    start_line: int
    severity: str  # "low" | "medium" | "high" | "critical"
    perspective: str  # e.g. "complexity", "dependency", "dead_code"
    suggestion: Optional[str] = None
    code_snippet: Optional[str] = None


@dataclass
class AuditReport:
    """A complete audit report for one session."""

    project_name: str
    session_id: str
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    total_files: int = 0
    total_symbols: int = 0
    findings: list[Finding] = field(default_factory=list)
    perspectives_run: list[str] = field(default_factory=list)
    summary: str = ""


class ReportGenerator:
    """Generates markdown reports from AuditReport data."""

    def generate(self, report: AuditReport) -> str:
        """Render the audit report as a markdown string."""
        lines = []

        # Header
        lines.append(f"# Nala Audit Report: {report.project_name}")
        lines.append(f"\n**Session:** `{report.session_id}`")
        lines.append(f"**Generated:** {report.created_at}")
        lines.append(f"**Files analysed:** {report.total_files}")
        lines.append(f"**Total symbols:** {report.total_symbols}")
        lines.append(f"**Perspectives run:** {', '.join(report.perspectives_run) or 'none'}")

        # Executive summary
        lines.append("\n---\n\n## Executive Summary\n")
        if report.summary:
            lines.append(report.summary)
        else:
            lines.append(self._auto_summary(report))

        # Findings by severity
        for sev in ("critical", "high", "medium", "low"):
            bucket = [f for f in report.findings if f.severity == sev]
            if not bucket:
                continue
            icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}[sev]
            lines.append(f"\n---\n\n## {icon} {sev.capitalize()} Findings ({len(bucket)})\n")
            for i, finding in enumerate(bucket, 1):
                lines.append(f"### {i}. {finding.title}")
                lines.append(f"\n**File:** `{finding.file_path}:{finding.start_line}`")
                lines.append(f"**Perspective:** {finding.perspective}")
                lines.append(f"\n{finding.description}")
                if finding.code_snippet:
                    lines.append(f"\n```\n{finding.code_snippet}\n```")
                if finding.suggestion:
                    lines.append(f"\n**Suggestion:** {finding.suggestion}")
                lines.append("")

        # Footer
        lines.append("\n---")
        lines.append("\n*Generated by Nala — terminal-first AI coding environment*")

        return "\n".join(lines)

    def _auto_summary(self, report: AuditReport) -> str:
        total = len(report.findings)
        critical = sum(1 for f in report.findings if f.severity == "critical")
        high = sum(1 for f in report.findings if f.severity == "high")

        if total == 0:
            return "No significant findings. The codebase looks healthy."

        parts = [f"Found **{total} findings** across {report.total_files} files."]
        if critical:
            parts.append(f"**{critical} critical** issues require immediate attention.")
        if high:
            parts.append(f"**{high} high-severity** issues should be addressed soon.")
        return " ".join(parts)
